### ISSUE TITLE
Incomplete scenes

### ISSUE THREAD

**Issue by Locutus73** [ilcato/homebridge-melcloud#2]
Hi,
it seems to be an issue with scenes.
Whenever I try to activate a scene that modifies more than one parameter (i.e. heating mode on three units), homebridge-melcloud reports that all is fine (I see all three units in heating mode in Home app), but just one or two parameters are modified (I see one or two units in heating mode in Melcloud app); after a while Home app gets in sync with Melcloud app (one or two units in heating mode).
This happens both if the scene modifies multiple parameters of one unit (i.e. one unit set to heat mode, 23 degrees Celsius, max fan speed) and if the scene modifies a single parameter of multiple units (i.e. heating mode on three units).
Homebridge output doesn’t report any problems and, capturing traffic on the Debian machine running it, I can see only ssl traffic. I think there may be a problem with multiple commands sent simultaneously; maybe a mutex mechanism could help.

Many thanks in advance.
Locutus73

**Comment by ilcato** [comment]
Will check it soon

**Comment by ilcato** [comment]
found error

**Comment by ilcato** [comment]
I committed a new index.js file. Are you able to install it manually on your setup and check if it works with your scenes ?

**Comment by Locutus73** [comment]
Hi,
I replaced /usr/lib/node_modules/homebridge-melcloud/index.js with the new one, changed the ownership as the original one, but, with the new one I cannot change any parameter, neither a single one directly on a unit without using scenes.
Did I miss something on how to install manually index.js?

Many thanks in advance.
Best regards.
Locutus73

**Comment by ilcato** [comment]
You need to simply restart homebridge

**Comment by ilcato** [comment]
do you see errors on the log?

**Comment by ilcato** [comment]
Try now please.

**Comment by Locutus73** [comment]
Now I can change successfully a single parameter again, but the scenes still don't work.
Do you want to organize a Skype session one of these days?

Thank you again.
Best regards.
Locutus73

**Comment by Locutus73** [comment]
Hi, I’m sorry I didn’t keep in touch (I didn’t used AC during spring).
Now it’s getting hot and I started again to use melcloud, but I still get this issue, using the last index.js both with the throttling parameter set to 1 or 2.
The system seems to be fine (a bit slow when updating data), I get no error logs, but when I try to activate a scene that modifies more than one parameter (i.e. cooling mode on three units), homebridge-melcloud reports that all is fine (I see all three units in cooling mode in Home app), but just one or two parameters are modified (I see one or two units in heating mode in Melcloud app); after a while Home app gets in sync with Melcloud app (one or two units in cooling mode).

Thank you again.
Best regards.
Locutus73
